### ISSUE TITLE
CRC failed in some situations

### ISSUE THREAD

**Issue by haonv206** [shinxz12/napas-qr-python#10]
* napas-pay-qr version: main
* Python version: 3.8.10
* Operating System: Ubuntu 22.04

### Description

calculate_checksum() function (in: qr_pay/crc.py) not always return a 4 digits hexa string.
For example: a check sumvalue of: 3104 just give 0xc20 hexa. Then, the final return of calculate_checksum() = "C20" (3 digits)

### Suggestions for improvement
Consider to change qr_pay/crc.py line 15:
```
return hex(checksum)[2:].upper()
```
to:
```
return '%04X' % checksum
```

**Comment by shinxz12** [comment]
Hi @haonv206, Thank you for your suggestion.
